# Generated by Django 5.1.7 on 2025-03-23 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0004_emprunt_returner_media_description_membre_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(default=datetime.date(2025, 3, 30)),
        ),
    ]
