# Generated by Django 5.1.7 on 2025-03-25 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0005_alter_emprunt_date_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(default=datetime.date(2025, 4, 1)),
        ),
    ]
